### ISSUE TITLE
request for weight files 

### ISSUE THREAD

**Issue by WandererGuy** [shraddhavijay/IFAKE#1]
@shraddhavijay 
First, wonderful project and paper. I have manage to run the web application , but the weight model is missing. 
Can the author kindly grant me request for access to image and video weight google drive.
My gmail:    manhtech264@gmail.com
Please grant me access in 
https://drive.google.com/drive/folders/1B4ODeK_QQ6XMFo6i6EEup1nZC6PllVfu?usp=sharing
https://drive.google.com/drive/folders/1irYZbRnr4Y7jKieSyhjxHxwk43oSMqh-?usp=sharing

I'm doing for my school research purpose, it would be super helpful. 
Thank you guys for this amazing project.

**Comment by WandererGuy** [comment]
@shraddhavijay thank you very much , i have accessed the folders.

**Comment by ADIbhosale007** [comment]
@shraddhavijay
Great project and paper! I've managed to run the web application, but the weight model is missing. Could you please give me access to the image and video weight files on Google Drive?

My gmail :  atulubale347@gmail.com

Please grant me access in
https://drive.google.com/drive/folders/1B4ODeK_QQ6XMFo6i6EEup1nZC6PllVfu?usp=sharing
https://drive.google.com/drive/folders/1irYZbRnr4Y7jKieSyhjxHxwk43oSMqh-?usp=sharing

I'm doing this for my personal and school. It would be really helpful.

**Comment by harshini-pokuru** [comment]
@shraddhavijay 
I appreciate the effort that went into this project - it looks amazing! I’ve been trying to get the web application running, but I’m unable to proceed without the weight model files. Would it be possible to gain access to them?

My Gmail: harshinipokuru@gmail.com

Google Drive Links:
[Folder 1](https://drive.google.com/drive/folders/1B4ODeK_QQ6XMFo6i6EEup1nZC6PllVfu?usp=sharing)
[Folder 2](https://drive.google.com/drive/folders/1irYZbRnr4Y7jKieSyhjxHxwk43oSMqh-?usp=sharing)

I’m working on a research project, and these files would be a huge help. Thanks in advance for any support!

**Comment by WandererGuy** [comment]
i have saved the author weights here, https://drive.google.com/drive/folders/1fIcqQfS6YXrtPyxADxew7svvsWo3jfW0?usp=sharing.
good luck bro!

**Comment by harshini-pokuru** [comment]
**Thanks a lot, @WandererGuy!** I really appreciate your help. 🙌
